[deps]
CPRL = "c13076dc-bdcd-48ba-bc88-4b44c2587ab3"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ReinforcementLearning = "158674fc-8238-5cab-b5ba-03dfc80d1318"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
